// This script scans the `functions/` directory and prepends a documentation comment block to each file.
// The comment includes:
//   - File purpose derived from the filename (converted to a readable title).
//   - Brief description of the module's role based on common patterns.
//   - Author and timestamp placeholders for future maintenance.
//   - A note that the file was auto‑generated and should be reviewed.
//
// Usage: `deno run --allow-read --allow-write scripts/batch_add_comments.ts`
//
import { walk } from "https://deno.land/std@0.224.0/fs/walk.ts";
import { ensureFile } from "https://deno.land/std@0.224.0/fs/ensure_file.ts";
import { join } from "https://deno.land/std@0.224.0/path/mod.ts";

const functionsDir = "./functions";
const now = new Date().toISOString();

function titleFromFileName(fileName: string): string {
  // Remove extension and split camelCase / snake_case / kebab-case into words
  const base = fileName.replace(/\.ts$/, "");
  const spaced = base
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/[_-]+/g, " ")
    .toLowerCase()
    .replace(/^\w/, (c) => c.toUpperCase());
  return spaced;
}

for await (const entry of walk(functionsDir, { exts: [".ts"], includeDirs: false })) {
  const filePath = entry.path;
  const fileName = entry.name;
  const title = titleFromFileName(fileName);

  // Read existing content
  const original = await Deno.readTextFile(filePath);

  // Build comment block
  const comment = `/**
+ * ${title}
+ *
+ * This module was automatically annotated by the batch comment script.
+ * It provides functionality related to ${title.toLowerCase()}.
+ *
+ * **NOTE**: Review the generated comments and adjust as needed to reflect the exact purpose.
+ *
+ * @author Generated by Antigravity
+ * @generated ${now}
+ */\n\n`;

  // Prepend comment if not already present
  if (!original.startsWith("/**")) {
    await ensureFile(filePath);
    await Deno.writeTextFile(filePath, comment + original);
    console.log(`Comment added to ${filePath}`);
  } else {
    console.log(`Skipping ${filePath} – already has a comment block`);
  }
}
console.log("Batch comment insertion complete.");
